#!/usr/bin/env sh

if [ -z "${CHECKS_RUN}" ]; then
  echo "Pre-commit checks will start as it is a manual commit"
  npx --no-install git-precommit-checks
  npx lint-staged --concurrent=false
  npx validate-branch-name
else
 echo "Skipping Pre-commit checks as they already executed"
fi