name: pxt-buildpush

on:
  push:
    # main/master has its own build that includes the crowdin key
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          sudo apt-get install xvfb
          sudo npm install -g pxt
          npm install
      - name: pxt ci
        run: |
          pxt ci
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          CHROME_BIN: chromium-browser
          DISPLAY: :99.0
          CI: true
