name: Release
on:
    push:
        branches:
            - main
            - staging
            - production

    pull_request:
        branches:
            - main

permissions:
    contents: read # for checkout

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        container:
            image: letssteam/makecode-toolchain:latest
            options: --user 1001 --security-opt no-new-privileges
        permissions:
            contents: write # to be able to publish a GitHub release
            issues: write # to be able to comment on released issues
            pull-requests: write # to be able to comment on released pull requests
            id-token: write # to enable use of OIDC for npm provenance
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
        steps:
            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v4
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: actions/checkout@v4
            - run: npm run setup
            - run: npm run ci
            - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
              run: npm audit signatures
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
